import { NextRequest, NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/server/supabaseAdmin";
import { getAuthUser } from "@/lib/server/auth";
import { generateRoadmapSchema } from "@/lib/server/validations";
import { errorResponse } from "@/lib/server/errors";
import { generateAiRoadmap } from "@/lib/server/aiRoadmap";

function clampHours(hours?: number) {
  if (hours == null) return 0;
  return Math.max(0, Math.min(hours, 500));
}

function resolveDueDate(dueInDays?: number) {
  if (!dueInDays || dueInDays <= 0) return null;
  const d = new Date();
  d.setDate(d.getDate() + dueInDays);
  return d.toISOString().slice(0, 10);
}

export async function POST(req: NextRequest) {
  try {
    const user = await getAuthUser(req);
    const { goal } = generateRoadmapSchema.parse(await req.json());

    const aiRoadmap = await generateAiRoadmap(goal);
    const title = aiRoadmap.roadmapTitle?.trim() || goal;

    const { data: roadmap, error } = await supabaseAdmin
      .from("roadmaps")
      .insert({ user_id: user.id, title, description: "Generated by AI", ai_generated: true })
      .select("*")
      .single();
    if (error || !roadmap) throw error;

    const tasksToInsert = (aiRoadmap.tasks || []).map((t) => ({
      roadmap_id: roadmap.id,
      title: t.title,
      priority: t.priority || "MEDIUM",
      estimated_hours: clampHours(t.estimatedHours),
      due_date: resolveDueDate(t.dueInDays),
      completed: false,
    }));

    if (tasksToInsert.length > 0) {
      await supabaseAdmin.from("roadmap_tasks").insert(tasksToInsert);
    }

    return NextResponse.json({
      id: roadmap.id,
      title: roadmap.title,
      description: roadmap.description,
      totalTasks: tasksToInsert.length,
      completedTasks: 0,
      progress: 0,
    });
  } catch (err) {
    return errorResponse(err);
  }
}